name: pr-checks

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: commit-msg-lint
        uses: wagoid/commitlint-github-action@v5
      - name: go-setup
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: no-format-change
        run: make no-format-change
      - name: go-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: v1.53.3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: qemu-setup
        uses: docker/setup-qemu-action@v2
      - name: docker-setup
        uses: docker/setup-buildx-action@v2
      - name: docker-build
        uses: docker/build-push-action@v4
        with:
          push: false
